// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/rooms/rooms.proto

package com_github_romatroskin_viqchat_rooms_service_rooms

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventType int32

const (
	EventType_Unknown     EventType = 0
	EventType_RoomCreated EventType = 1
	EventType_RoomUpdated EventType = 2
	EventType_RoomDeleted EventType = 3
)

var EventType_name = map[int32]string{
	0: "Unknown",
	1: "RoomCreated",
	2: "RoomUpdated",
	3: "RoomDeleted",
}

var EventType_value = map[string]int32{
	"Unknown":     0,
	"RoomCreated": 1,
	"RoomUpdated": 2,
	"RoomDeleted": 3,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}

func (EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f1532792d13ef8c0, []int{0}
}

type Event struct {
	Type                 EventType `protobuf:"varint,1,opt,name=type,proto3,enum=com.github.romatroskin.viqchat.rooms.service.rooms.EventType" json:"type,omitempty"`
	Room                 *Room     `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1532792d13ef8c0, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetType() EventType {
	if m != nil {
		return m.Type
	}
	return EventType_Unknown
}

func (m *Event) GetRoom() *Room {
	if m != nil {
		return m.Room
	}
	return nil
}

type Room struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Owner                string   `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Topic                string   `protobuf:"bytes,4,opt,name=topic,proto3" json:"topic,omitempty"`
	Created              int64    `protobuf:"varint,5,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64    `protobuf:"varint,6,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Room) Reset()         { *m = Room{} }
func (m *Room) String() string { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()    {}
func (*Room) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1532792d13ef8c0, []int{1}
}

func (m *Room) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Room.Unmarshal(m, b)
}
func (m *Room) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Room.Marshal(b, m, deterministic)
}
func (m *Room) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Room.Merge(m, src)
}
func (m *Room) XXX_Size() int {
	return xxx_messageInfo_Room.Size(m)
}
func (m *Room) XXX_DiscardUnknown() {
	xxx_messageInfo_Room.DiscardUnknown(m)
}

var xxx_messageInfo_Room proto.InternalMessageInfo

func (m *Room) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Room) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Room) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Room) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Room) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Room) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type CreateRequest struct {
	Room                 *Room    `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	Participants         []string `protobuf:"bytes,3,rep,name=participants,proto3" json:"participants,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1532792d13ef8c0, []int{2}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetRoom() *Room {
	if m != nil {
		return m.Room
	}
	return nil
}

func (m *CreateRequest) GetParticipants() []string {
	if m != nil {
		return m.Participants
	}
	return nil
}

type ListRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1532792d13ef8c0, []int{3}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type Response struct {
	Room                 *Room    `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	Rooms                []*Room  `protobuf:"bytes,2,rep,name=rooms,proto3" json:"rooms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1532792d13ef8c0, []int{4}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetRoom() *Room {
	if m != nil {
		return m.Room
	}
	return nil
}

func (m *Response) GetRooms() []*Room {
	if m != nil {
		return m.Rooms
	}
	return nil
}

func init() {
	proto.RegisterEnum("com.github.romatroskin.viqchat.rooms.service.rooms.EventType", EventType_name, EventType_value)
	proto.RegisterType((*Event)(nil), "com.github.romatroskin.viqchat.rooms.service.rooms.Event")
	proto.RegisterType((*Room)(nil), "com.github.romatroskin.viqchat.rooms.service.rooms.Room")
	proto.RegisterType((*CreateRequest)(nil), "com.github.romatroskin.viqchat.rooms.service.rooms.CreateRequest")
	proto.RegisterType((*ListRequest)(nil), "com.github.romatroskin.viqchat.rooms.service.rooms.ListRequest")
	proto.RegisterType((*Response)(nil), "com.github.romatroskin.viqchat.rooms.service.rooms.Response")
}

func init() { proto.RegisterFile("proto/rooms/rooms.proto", fileDescriptor_f1532792d13ef8c0) }

var fileDescriptor_f1532792d13ef8c0 = []byte{
	// 410 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xcf, 0x8a, 0xd5, 0x30,
	0x14, 0xc6, 0x27, 0xfd, 0x73, 0xc7, 0x7b, 0xaa, 0xe3, 0x25, 0x88, 0x06, 0x57, 0xa5, 0x20, 0x14,
	0x17, 0x15, 0xea, 0xc6, 0x85, 0x22, 0xa2, 0x2e, 0xc4, 0x41, 0x30, 0x38, 0x0f, 0xd0, 0x69, 0x0f,
	0x4e, 0x18, 0x9b, 0x64, 0x92, 0xf4, 0x0e, 0xb3, 0x74, 0x25, 0xe8, 0x43, 0xb8, 0xf5, 0x31, 0x25,
	0xc9, 0xed, 0xe0, 0x2c, 0xed, 0xdc, 0x4d, 0xe9, 0xf7, 0x3b, 0xa7, 0x5f, 0xcf, 0xc9, 0x57, 0x0a,
	0x8f, 0xb4, 0x51, 0x4e, 0x3d, 0x33, 0x4a, 0x8d, 0x36, 0x5e, 0x9b, 0x40, 0x68, 0xdb, 0xab, 0xb1,
	0xf9, 0x2a, 0xdc, 0xd9, 0x74, 0xda, 0x18, 0x35, 0x76, 0xce, 0x28, 0x7b, 0x2e, 0x64, 0xb3, 0x15,
	0x17, 0xfd, 0x59, 0xe7, 0x9a, 0xd8, 0x6b, 0xd1, 0x6c, 0x45, 0x8f, 0x51, 0x55, 0x7f, 0x08, 0xe4,
	0xef, 0xb7, 0x28, 0x1d, 0xfd, 0x0c, 0x99, 0xbb, 0xd2, 0xc8, 0x48, 0x49, 0xea, 0xa3, 0xf6, 0x55,
	0xf3, 0xff, 0x66, 0x4d, 0x30, 0xfa, 0x72, 0xa5, 0x91, 0x07, 0x2b, 0x7a, 0x0c, 0x99, 0x2f, 0xb0,
	0xa4, 0x24, 0x75, 0xd1, 0xbe, 0x58, 0x62, 0xc9, 0x95, 0x1a, 0x79, 0x70, 0xa9, 0x7e, 0x12, 0xc8,
	0xbc, 0xa4, 0x47, 0x90, 0x88, 0x21, 0xcc, 0xb9, 0xe6, 0x89, 0x18, 0x28, 0x85, 0x4c, 0x76, 0x23,
	0x86, 0xd7, 0xac, 0x79, 0xb8, 0xa7, 0x0f, 0x20, 0x57, 0x97, 0x12, 0x0d, 0x4b, 0x03, 0x8c, 0xc2,
	0x53, 0xa7, 0xb4, 0xe8, 0x59, 0x16, 0x69, 0x10, 0x94, 0xc1, 0x61, 0x6f, 0xb0, 0x73, 0x38, 0xb0,
	0xbc, 0x24, 0x75, 0xca, 0x67, 0xe9, 0x2b, 0x93, 0x1e, 0x42, 0x65, 0x15, 0x2b, 0x3b, 0x59, 0x7d,
	0x27, 0x70, 0xef, 0x6d, 0xe8, 0xe2, 0x78, 0x31, 0xa1, 0x75, 0xd7, 0xcb, 0x92, 0x7d, 0x2c, 0x4b,
	0x2b, 0xb8, 0xab, 0x3b, 0xe3, 0x44, 0x2f, 0x74, 0x27, 0x9d, 0x65, 0x69, 0x99, 0xd6, 0x6b, 0x7e,
	0x83, 0x55, 0x4f, 0xa0, 0x38, 0x16, 0xd6, 0xcd, 0x03, 0x3c, 0x84, 0xd5, 0x64, 0xd1, 0x7c, 0x98,
	0x8f, 0x66, 0xa7, 0x7c, 0xc4, 0x77, 0x38, 0x5a, 0xad, 0xa4, 0xc5, 0x3d, 0x4f, 0xf9, 0x09, 0xf2,
	0xc0, 0x58, 0x52, 0xa6, 0xb7, 0xb2, 0x8b, 0x36, 0x4f, 0x3f, 0xc2, 0xfa, 0xfa, 0x1b, 0xa2, 0x05,
	0x1c, 0x9e, 0xc8, 0x73, 0xa9, 0x2e, 0xe5, 0xe6, 0x80, 0xde, 0x87, 0xc2, 0x37, 0xc6, 0x23, 0x1f,
	0x36, 0x64, 0x06, 0x27, 0x31, 0x8f, 0x4d, 0x32, 0x83, 0x77, 0xf8, 0x0d, 0x3d, 0x48, 0xdb, 0xdf,
	0x09, 0xe4, 0x9e, 0x58, 0xfa, 0x8b, 0xc0, 0x2a, 0x3e, 0x49, 0xdf, 0x2c, 0x19, 0xf1, 0x46, 0xd0,
	0x8f, 0x5f, 0x2e, 0xda, 0x72, 0x17, 0x40, 0x75, 0x40, 0x7f, 0x10, 0xc8, 0x7c, 0x6e, 0xf4, 0xf5,
	0x12, 0xa3, 0x7f, 0x12, 0xbf, 0xed, 0x24, 0xa7, 0xab, 0xf0, 0xdf, 0x78, 0xfe, 0x37, 0x00, 0x00,
	0xff, 0xff, 0xbb, 0x46, 0x6d, 0x0b, 0x52, 0x04, 0x00, 0x00,
}
