// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/users/users.proto

package com_github_romatroskin_viqchat_service_users

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventType int32

const (
	EventType_Unknown     EventType = 0
	EventType_UserCreated EventType = 1
	EventType_UserUpdated EventType = 2
	EventType_UserDeleted EventType = 3
)

var EventType_name = map[int32]string{
	0: "Unknown",
	1: "UserCreated",
	2: "UserUpdated",
	3: "UserDeleted",
}

var EventType_value = map[string]int32{
	"Unknown":     0,
	"UserCreated": 1,
	"UserUpdated": 2,
	"UserDeleted": 3,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}

func (EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb78b70ef3ad6f73, []int{0}
}

type Event struct {
	Type                 EventType `protobuf:"varint,1,opt,name=type,proto3,enum=com.github.romatroskin.viqchat.service.users.EventType" json:"type,omitempty"`
	User                 *User     `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb78b70ef3ad6f73, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetType() EventType {
	if m != nil {
		return m.Type
	}
	return EventType_Unknown
}

func (m *Event) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Displayname          string   `protobuf:"bytes,4,opt,name=displayname,proto3" json:"displayname,omitempty"`
	Bio                  string   `protobuf:"bytes,5,opt,name=bio,proto3" json:"bio,omitempty"`
	Created              int64    `protobuf:"varint,6,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64    `protobuf:"varint,7,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb78b70ef3ad6f73, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetDisplayname() string {
	if m != nil {
		return m.Displayname
	}
	return ""
}

func (m *User) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func (m *User) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *User) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type CreateRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	ValidateOnly         bool     `protobuf:"varint,2,opt,name=validate_only,json=validateOnly,proto3" json:"validate_only,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb78b70ef3ad6f73, []int{2}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *CreateRequest) GetValidateOnly() bool {
	if m != nil {
		return m.ValidateOnly
	}
	return false
}

type CreateResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb78b70ef3ad6f73, []int{3}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type DeleteRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb78b70ef3ad6f73, []int{4}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb78b70ef3ad6f73, []int{5}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

type ReadRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb78b70ef3ad6f73, []int{6}
}

func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (m *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(m, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ReadRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type ReadResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadResponse) Reset()         { *m = ReadResponse{} }
func (m *ReadResponse) String() string { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()    {}
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb78b70ef3ad6f73, []int{7}
}

func (m *ReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadResponse.Unmarshal(m, b)
}
func (m *ReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadResponse.Marshal(b, m, deterministic)
}
func (m *ReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadResponse.Merge(m, src)
}
func (m *ReadResponse) XXX_Size() int {
	return xxx_messageInfo_ReadResponse.Size(m)
}
func (m *ReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadResponse proto.InternalMessageInfo

func (m *ReadResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb78b70ef3ad6f73, []int{8}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb78b70ef3ad6f73, []int{9}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type SearchRequest struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb78b70ef3ad6f73, []int{10}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type SearchResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb78b70ef3ad6f73, []int{11}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterEnum("com.github.romatroskin.viqchat.service.users.EventType", EventType_name, EventType_value)
	proto.RegisterType((*Event)(nil), "com.github.romatroskin.viqchat.service.users.Event")
	proto.RegisterType((*User)(nil), "com.github.romatroskin.viqchat.service.users.User")
	proto.RegisterType((*CreateRequest)(nil), "com.github.romatroskin.viqchat.service.users.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "com.github.romatroskin.viqchat.service.users.CreateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "com.github.romatroskin.viqchat.service.users.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "com.github.romatroskin.viqchat.service.users.DeleteResponse")
	proto.RegisterType((*ReadRequest)(nil), "com.github.romatroskin.viqchat.service.users.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "com.github.romatroskin.viqchat.service.users.ReadResponse")
	proto.RegisterType((*UpdateRequest)(nil), "com.github.romatroskin.viqchat.service.users.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "com.github.romatroskin.viqchat.service.users.UpdateResponse")
	proto.RegisterType((*SearchRequest)(nil), "com.github.romatroskin.viqchat.service.users.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "com.github.romatroskin.viqchat.service.users.SearchResponse")
}

func init() { proto.RegisterFile("proto/users/users.proto", fileDescriptor_bb78b70ef3ad6f73) }

var fileDescriptor_bb78b70ef3ad6f73 = []byte{
	// 543 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x4d, 0xab, 0xd3, 0x4c,
	0x14, 0xee, 0xb4, 0x4d, 0x7b, 0x7b, 0x7a, 0x93, 0x37, 0x0c, 0x17, 0xde, 0xd0, 0x8d, 0x61, 0x44,
	0x28, 0x22, 0x11, 0x7a, 0x17, 0xe2, 0xc7, 0xce, 0x0f, 0x84, 0xbb, 0x10, 0xa2, 0x55, 0x71, 0x23,
	0x69, 0x32, 0xd8, 0x70, 0xd3, 0x99, 0x34, 0x93, 0x54, 0x02, 0x82, 0x2b, 0xff, 0x85, 0x3f, 0xc0,
	0xa5, 0x3f, 0x51, 0x66, 0x26, 0xe9, 0x6d, 0x2e, 0xb8, 0x98, 0xda, 0x4d, 0xe9, 0xf9, 0x7e, 0xf2,
	0x9c, 0xe7, 0x24, 0xf0, 0x7f, 0x5e, 0xf0, 0x92, 0x3f, 0xac, 0x04, 0x2d, 0x84, 0xfe, 0x0d, 0x94,
	0x07, 0x3f, 0x88, 0xf9, 0x26, 0xf8, 0x92, 0x96, 0xeb, 0x6a, 0x15, 0x14, 0x7c, 0x13, 0x95, 0x05,
	0x17, 0xd7, 0x29, 0x0b, 0x76, 0xe9, 0x36, 0x5e, 0x47, 0x65, 0x20, 0x68, 0xb1, 0x4b, 0x63, 0x1a,
	0xa8, 0x1a, 0xf2, 0x13, 0x81, 0xf5, 0x72, 0x47, 0x59, 0x89, 0xaf, 0x60, 0x58, 0xd6, 0x39, 0xf5,
	0x90, 0x8f, 0xe6, 0xce, 0xe2, 0x51, 0x60, 0xd2, 0x26, 0x50, 0x2d, 0xde, 0xd5, 0x39, 0x0d, 0x55,
	0x13, 0xfc, 0x0a, 0x86, 0x32, 0xe0, 0xf5, 0x7d, 0x34, 0x9f, 0x2e, 0x16, 0x66, 0xcd, 0x96, 0x82,
	0x16, 0xa1, 0xaa, 0x27, 0xbf, 0x11, 0x0c, 0xa5, 0x89, 0x1d, 0xe8, 0xa7, 0x89, 0xc2, 0x36, 0x09,
	0xfb, 0x69, 0x82, 0x67, 0x70, 0x26, 0x13, 0x58, 0xb4, 0xa1, 0x6a, 0xc8, 0x24, 0xdc, 0xdb, 0xf8,
	0x02, 0xac, 0x7c, 0xcd, 0x19, 0xf5, 0x06, 0x2a, 0xa0, 0x0d, 0xec, 0xc3, 0x34, 0x49, 0x45, 0x9e,
	0x45, 0xb5, 0x2a, 0x1a, 0xaa, 0xd8, 0xa1, 0x0b, 0xbb, 0x30, 0x58, 0xa5, 0xdc, 0xb3, 0x54, 0x44,
	0xfe, 0xc5, 0x1e, 0x8c, 0xe3, 0x82, 0x46, 0x25, 0x4d, 0xbc, 0x91, 0x8f, 0xe6, 0x83, 0xb0, 0x35,
	0x65, 0xa4, 0xca, 0x13, 0x15, 0x19, 0xeb, 0x48, 0x63, 0x92, 0x6f, 0x60, 0x3f, 0x57, 0x49, 0x21,
	0xdd, 0x56, 0x54, 0x94, 0x7b, 0x2e, 0xd0, 0xbf, 0x71, 0x81, 0xef, 0x82, 0xbd, 0x8b, 0xb2, 0x54,
	0x4e, 0xf9, 0xcc, 0x59, 0x56, 0xab, 0xe7, 0x3e, 0x0b, 0xcf, 0x5b, 0xe7, 0x1b, 0x96, 0xd5, 0xe4,
	0x23, 0x38, 0xed, 0x74, 0x91, 0x73, 0x26, 0xe8, 0xa9, 0xc6, 0x93, 0x3b, 0x60, 0xbf, 0xa0, 0x19,
	0xbd, 0x79, 0xae, 0x5b, 0x2b, 0x21, 0x2e, 0x38, 0x6d, 0x82, 0x1e, 0x4d, 0x2e, 0x61, 0x1a, 0xd2,
	0x28, 0xf9, 0x4b, 0xc1, 0xcd, 0x9e, 0xfa, 0x07, 0x7b, 0x22, 0xef, 0xe1, 0x5c, 0x17, 0x9d, 0x18,
	0xff, 0x07, 0xb0, 0x97, 0x6a, 0x45, 0x27, 0xde, 0x8b, 0xa4, 0xbc, 0x6d, 0x7c, 0x62, 0xc8, 0xf7,
	0xc0, 0x7e, 0x4b, 0xa3, 0x22, 0x5e, 0xb7, 0x90, 0x2f, 0xc0, 0xda, 0x56, 0xb4, 0xa8, 0x1b, 0x12,
	0xb5, 0x41, 0x3e, 0x81, 0xd3, 0xa6, 0x35, 0x00, 0x5e, 0x83, 0xa5, 0x9a, 0x79, 0xc8, 0x1f, 0x1c,
	0x89, 0x40, 0x37, 0xb8, 0x7f, 0x05, 0x93, 0xfd, 0x6d, 0xe3, 0x29, 0x8c, 0x97, 0xec, 0x9a, 0xf1,
	0xaf, 0xcc, 0xed, 0xe1, 0xff, 0x60, 0x2a, 0x13, 0xb5, 0xda, 0x12, 0x17, 0xb5, 0x0e, 0xcd, 0x45,
	0xe2, 0xf6, 0x5b, 0x87, 0x16, 0x45, 0xe2, 0x0e, 0x16, 0xbf, 0x2c, 0xb0, 0xa4, 0x47, 0xe0, 0x1f,
	0x08, 0x46, 0xba, 0x12, 0x3f, 0x35, 0x03, 0xd7, 0xb9, 0xad, 0xd9, 0xb3, 0xe3, 0x8a, 0x1b, 0x7d,
	0xf6, 0xf0, 0x77, 0x18, 0x4a, 0xb1, 0xe1, 0xc7, 0x66, 0x7d, 0x0e, 0x54, 0x3d, 0x7b, 0x72, 0x4c,
	0xe9, 0x1e, 0x80, 0x24, 0x42, 0x33, 0x66, 0x4a, 0x44, 0x47, 0xcc, 0xa6, 0x44, 0x74, 0x05, 0xdb,
	0xe0, 0xd0, 0x8b, 0x32, 0xc5, 0xd1, 0x79, 0x29, 0x98, 0xe2, 0xb8, 0xf5, 0xc2, 0xd0, 0x38, 0xb4,
	0x98, 0x4d, 0x71, 0x74, 0x2e, 0xc5, 0x14, 0x47, 0xf7, 0x7e, 0x48, 0x6f, 0x35, 0x52, 0x1f, 0xd3,
	0xcb, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xea, 0xa4, 0x0c, 0xa4, 0x67, 0x07, 0x00, 0x00,
}
