// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/messages/messages.proto

package com_github_romatroskin_viqchat_messages_service_messages

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ChatMessageType int32

const (
	ChatMessageType_Text  ChatMessageType = 0
	ChatMessageType_Voice ChatMessageType = 1
	ChatMessageType_Video ChatMessageType = 2
)

var ChatMessageType_name = map[int32]string{
	0: "Text",
	1: "Voice",
	2: "Video",
}

var ChatMessageType_value = map[string]int32{
	"Text":  0,
	"Voice": 1,
	"Video": 2,
}

func (x ChatMessageType) String() string {
	return proto.EnumName(ChatMessageType_name, int32(x))
}

func (ChatMessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c1b26220ebf1a08a, []int{0}
}

type ChatMessage struct {
	Id                   string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Channel              string          `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	From                 string          `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	Parent               string          `protobuf:"bytes,4,opt,name=parent,proto3" json:"parent,omitempty"`
	Content              string          `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Type                 ChatMessageType `protobuf:"varint,6,opt,name=type,proto3,enum=com.github.romatroskin.viqchat.messages.service.messages.ChatMessageType" json:"type,omitempty"`
	Created              int64           `protobuf:"varint,7,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64           `protobuf:"varint,8,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ChatMessage) Reset()         { *m = ChatMessage{} }
func (m *ChatMessage) String() string { return proto.CompactTextString(m) }
func (*ChatMessage) ProtoMessage()    {}
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b26220ebf1a08a, []int{0}
}

func (m *ChatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMessage.Unmarshal(m, b)
}
func (m *ChatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMessage.Marshal(b, m, deterministic)
}
func (m *ChatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMessage.Merge(m, src)
}
func (m *ChatMessage) XXX_Size() int {
	return xxx_messageInfo_ChatMessage.Size(m)
}
func (m *ChatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMessage proto.InternalMessageInfo

func (m *ChatMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ChatMessage) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *ChatMessage) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *ChatMessage) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *ChatMessage) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ChatMessage) GetType() ChatMessageType {
	if m != nil {
		return m.Type
	}
	return ChatMessageType_Text
}

func (m *ChatMessage) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *ChatMessage) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type ListRequest struct {
	Channel              string   `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b26220ebf1a08a, []int{1}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

type Response struct {
	Message              *ChatMessage   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Messages             []*ChatMessage `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b26220ebf1a08a, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMessage() *ChatMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Response) GetMessages() []*ChatMessage {
	if m != nil {
		return m.Messages
	}
	return nil
}

func init() {
	proto.RegisterEnum("com.github.romatroskin.viqchat.messages.service.messages.ChatMessageType", ChatMessageType_name, ChatMessageType_value)
	proto.RegisterType((*ChatMessage)(nil), "com.github.romatroskin.viqchat.messages.service.messages.ChatMessage")
	proto.RegisterType((*ListRequest)(nil), "com.github.romatroskin.viqchat.messages.service.messages.ListRequest")
	proto.RegisterType((*Response)(nil), "com.github.romatroskin.viqchat.messages.service.messages.Response")
}

func init() { proto.RegisterFile("proto/messages/messages.proto", fileDescriptor_c1b26220ebf1a08a) }

var fileDescriptor_c1b26220ebf1a08a = []byte{
	// 368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0xc1, 0x4e, 0xe3, 0x30,
	0x10, 0xad, 0xd3, 0xb4, 0x4d, 0xa7, 0xab, 0x6e, 0xe5, 0xc3, 0xca, 0x5a, 0x69, 0xa5, 0x28, 0x97,
	0xad, 0xf6, 0x90, 0x15, 0xe5, 0xc2, 0x19, 0xc4, 0x01, 0x09, 0x2e, 0x51, 0x05, 0x27, 0x84, 0xdc,
	0x64, 0x68, 0x2c, 0x48, 0x9c, 0xda, 0x6e, 0x45, 0xff, 0x02, 0x09, 0xfe, 0x86, 0x7f, 0xe0, 0x9b,
	0x50, 0xdd, 0x24, 0x0a, 0x1c, 0x4b, 0x6e, 0xf3, 0xde, 0x9b, 0x3c, 0xbf, 0x19, 0xc7, 0xf0, 0xa7,
	0x50, 0xd2, 0xc8, 0xff, 0x19, 0x6a, 0xcd, 0x97, 0xa8, 0xeb, 0x22, 0xb4, 0x3c, 0x3d, 0x89, 0x65,
	0x16, 0x2e, 0x85, 0x49, 0xd7, 0x8b, 0x50, 0xc9, 0x8c, 0x1b, 0x25, 0xf5, 0x83, 0xc8, 0xc3, 0x8d,
	0x58, 0xc5, 0x29, 0x37, 0x61, 0xdd, 0xae, 0x51, 0x6d, 0x44, 0x8c, 0x35, 0x11, 0x3c, 0x3b, 0x30,
	0x3a, 0x4b, 0xb9, 0xb9, 0xda, 0x13, 0x74, 0x0c, 0x8e, 0x48, 0x18, 0xf1, 0xc9, 0x74, 0x18, 0x39,
	0x22, 0xa1, 0x0c, 0x06, 0x71, 0xca, 0xf3, 0x1c, 0x1f, 0x99, 0x63, 0xc9, 0x0a, 0x52, 0x0a, 0xee,
	0xbd, 0x92, 0x19, 0xeb, 0x5a, 0xda, 0xd6, 0xf4, 0x17, 0xf4, 0x0b, 0xae, 0x30, 0x37, 0xcc, 0xb5,
	0x6c, 0x89, 0xac, 0x8b, 0xcc, 0xcd, 0x4e, 0xe8, 0x95, 0x2e, 0x7b, 0x48, 0x6f, 0xc1, 0x35, 0xdb,
	0x02, 0x59, 0xdf, 0x27, 0xd3, 0xf1, 0xec, 0x22, 0x3c, 0x74, 0x90, 0xb0, 0x31, 0xc4, 0x7c, 0x5b,
	0x60, 0x64, 0x6d, 0xed, 0xc1, 0x0a, 0xb9, 0xc1, 0x84, 0x0d, 0x7c, 0x32, 0xed, 0x46, 0x15, 0xdc,
	0x29, 0xeb, 0x22, 0xb1, 0x8a, 0xb7, 0x57, 0x4a, 0x18, 0xfc, 0x85, 0xd1, 0xa5, 0xd0, 0x26, 0xc2,
	0xd5, 0x1a, 0xb5, 0x69, 0x6e, 0x80, 0x7c, 0xda, 0x40, 0xf0, 0x4e, 0xc0, 0x8b, 0x50, 0x17, 0x32,
	0xd7, 0x48, 0xef, 0x60, 0x50, 0x66, 0xb1, 0x6d, 0xa3, 0xd9, 0x79, 0x2b, 0xb3, 0x44, 0x95, 0x2b,
	0xe5, 0xe0, 0x55, 0x0d, 0xcc, 0xf1, 0xbb, 0xed, 0x9d, 0x50, 0xdb, 0xfe, 0x3b, 0x82, 0x9f, 0x5f,
	0xd6, 0x48, 0x3d, 0x70, 0xe7, 0xf8, 0x64, 0x26, 0x1d, 0x3a, 0x84, 0xde, 0xb5, 0x14, 0x31, 0x4e,
	0x88, 0x2d, 0x45, 0x82, 0x72, 0xe2, 0xcc, 0xde, 0x1c, 0xf8, 0xd1, 0xf8, 0x46, 0xd3, 0x57, 0x02,
	0xbd, 0x1b, 0x25, 0x0c, 0xd2, 0x76, 0xe2, 0xfd, 0x3e, 0x3d, 0xdc, 0xa6, 0xba, 0x9c, 0xa0, 0x43,
	0x5f, 0x08, 0xb8, 0xbb, 0x5b, 0xfd, 0x4e, 0xaa, 0xc6, 0x5f, 0xd1, 0x4e, 0xaa, 0x45, 0xdf, 0x3e,
	0xdf, 0xe3, 0x8f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1c, 0x47, 0x5a, 0x94, 0xdf, 0x03, 0x00, 0x00,
}
