// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/otp/otp.proto

package com_github_romatroskin_viqchat_otp_service_otp

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Otp service

func NewOtpEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Otp service

type OtpService interface {
	Generate(ctx context.Context, in *GenerateRequest, opts ...client.CallOption) (*GenerateResponse, error)
	Verify(ctx context.Context, in *VerifyRequest, opts ...client.CallOption) (*VerifyResponse, error)
}

type otpService struct {
	c    client.Client
	name string
}

func NewOtpService(name string, c client.Client) OtpService {
	return &otpService{
		c:    c,
		name: name,
	}
}

func (c *otpService) Generate(ctx context.Context, in *GenerateRequest, opts ...client.CallOption) (*GenerateResponse, error) {
	req := c.c.NewRequest(c.name, "Otp.Generate", in)
	out := new(GenerateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *otpService) Verify(ctx context.Context, in *VerifyRequest, opts ...client.CallOption) (*VerifyResponse, error) {
	req := c.c.NewRequest(c.name, "Otp.Verify", in)
	out := new(VerifyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Otp service

type OtpHandler interface {
	Generate(context.Context, *GenerateRequest, *GenerateResponse) error
	Verify(context.Context, *VerifyRequest, *VerifyResponse) error
}

func RegisterOtpHandler(s server.Server, hdlr OtpHandler, opts ...server.HandlerOption) error {
	type otp interface {
		Generate(ctx context.Context, in *GenerateRequest, out *GenerateResponse) error
		Verify(ctx context.Context, in *VerifyRequest, out *VerifyResponse) error
	}
	type Otp struct {
		otp
	}
	h := &otpHandler{hdlr}
	return s.Handle(s.NewHandler(&Otp{h}, opts...))
}

type otpHandler struct {
	OtpHandler
}

func (h *otpHandler) Generate(ctx context.Context, in *GenerateRequest, out *GenerateResponse) error {
	return h.OtpHandler.Generate(ctx, in, out)
}

func (h *otpHandler) Verify(ctx context.Context, in *VerifyRequest, out *VerifyResponse) error {
	return h.OtpHandler.Verify(ctx, in, out)
}
