// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/otp/otp.proto

package com_github_romatroskin_viqchat_otp_service_otp

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GenerateRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateRequest) Reset()         { *m = GenerateRequest{} }
func (m *GenerateRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateRequest) ProtoMessage()    {}
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7373511ce20dc1f7, []int{0}
}

func (m *GenerateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateRequest.Unmarshal(m, b)
}
func (m *GenerateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateRequest.Marshal(b, m, deterministic)
}
func (m *GenerateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateRequest.Merge(m, src)
}
func (m *GenerateRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateRequest.Size(m)
}
func (m *GenerateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateRequest proto.InternalMessageInfo

func (m *GenerateRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type GenerateResponse struct {
	Passcode             string   `protobuf:"bytes,1,opt,name=passcode,proto3" json:"passcode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateResponse) Reset()         { *m = GenerateResponse{} }
func (m *GenerateResponse) String() string { return proto.CompactTextString(m) }
func (*GenerateResponse) ProtoMessage()    {}
func (*GenerateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7373511ce20dc1f7, []int{1}
}

func (m *GenerateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateResponse.Unmarshal(m, b)
}
func (m *GenerateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateResponse.Marshal(b, m, deterministic)
}
func (m *GenerateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateResponse.Merge(m, src)
}
func (m *GenerateResponse) XXX_Size() int {
	return xxx_messageInfo_GenerateResponse.Size(m)
}
func (m *GenerateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateResponse proto.InternalMessageInfo

func (m *GenerateResponse) GetPasscode() string {
	if m != nil {
		return m.Passcode
	}
	return ""
}

type VerifyRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Passcode             string   `protobuf:"bytes,2,opt,name=passcode,proto3" json:"passcode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyRequest) Reset()         { *m = VerifyRequest{} }
func (m *VerifyRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyRequest) ProtoMessage()    {}
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7373511ce20dc1f7, []int{2}
}

func (m *VerifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyRequest.Unmarshal(m, b)
}
func (m *VerifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyRequest.Marshal(b, m, deterministic)
}
func (m *VerifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyRequest.Merge(m, src)
}
func (m *VerifyRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyRequest.Size(m)
}
func (m *VerifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyRequest proto.InternalMessageInfo

func (m *VerifyRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *VerifyRequest) GetPasscode() string {
	if m != nil {
		return m.Passcode
	}
	return ""
}

type VerifyResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyResponse) Reset()         { *m = VerifyResponse{} }
func (m *VerifyResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyResponse) ProtoMessage()    {}
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7373511ce20dc1f7, []int{3}
}

func (m *VerifyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyResponse.Unmarshal(m, b)
}
func (m *VerifyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyResponse.Marshal(b, m, deterministic)
}
func (m *VerifyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyResponse.Merge(m, src)
}
func (m *VerifyResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyResponse.Size(m)
}
func (m *VerifyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyResponse proto.InternalMessageInfo

func (m *VerifyResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*GenerateRequest)(nil), "com.github.romatroskin.viqchat.otp.service.otp.GenerateRequest")
	proto.RegisterType((*GenerateResponse)(nil), "com.github.romatroskin.viqchat.otp.service.otp.GenerateResponse")
	proto.RegisterType((*VerifyRequest)(nil), "com.github.romatroskin.viqchat.otp.service.otp.VerifyRequest")
	proto.RegisterType((*VerifyResponse)(nil), "com.github.romatroskin.viqchat.otp.service.otp.VerifyResponse")
}

func init() { proto.RegisterFile("proto/otp/otp.proto", fileDescriptor_7373511ce20dc1f7) }

var fileDescriptor_7373511ce20dc1f7 = []byte{
	// 242 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0x2f, 0x29, 0x00, 0x61, 0x3d, 0x30, 0x4f, 0x48, 0x2f, 0x39, 0x3f, 0x57, 0x2f,
	0x3d, 0xb3, 0x24, 0xa3, 0x34, 0x49, 0xaf, 0x28, 0x3f, 0x37, 0xb1, 0xa4, 0x28, 0xbf, 0x38, 0x3b,
	0x33, 0x4f, 0xaf, 0x2c, 0xb3, 0x30, 0x39, 0x23, 0xb1, 0x44, 0x0f, 0xa4, 0xb2, 0x38, 0xb5, 0xa8,
	0x2c, 0x33, 0x39, 0x15, 0xc4, 0x56, 0x52, 0xe7, 0xe2, 0x77, 0x4f, 0xcd, 0x4b, 0x2d, 0x4a, 0x2c,
	0x49, 0x0d, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe1, 0x62, 0x2d, 0xc8, 0xc8, 0xcf,
	0x4b, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x70, 0x94, 0xf4, 0xb8, 0x04, 0x10, 0x0a,
	0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0xa4, 0xb8, 0x38, 0x0a, 0x12, 0x8b, 0x8b, 0x93, 0xf3,
	0x53, 0x60, 0x8a, 0xe1, 0x7c, 0x25, 0x47, 0x2e, 0xde, 0xb0, 0xd4, 0xa2, 0xcc, 0xb4, 0x4a, 0xbc,
	0xc6, 0xa2, 0x18, 0xc1, 0x84, 0x66, 0x84, 0x1a, 0x17, 0x1f, 0xcc, 0x08, 0xa8, 0x85, 0x22, 0x5c,
	0xac, 0x25, 0xf9, 0xd9, 0xa9, 0x79, 0x30, 0x33, 0xc0, 0x1c, 0xa3, 0xc5, 0x4c, 0x5c, 0xcc, 0xfe,
	0x25, 0x05, 0x42, 0xfd, 0x8c, 0x5c, 0x1c, 0x30, 0x37, 0x0a, 0xd9, 0x93, 0x18, 0x12, 0x7a, 0x68,
	0xc1, 0x20, 0xe5, 0x40, 0xbe, 0x01, 0x10, 0xd7, 0x2a, 0x31, 0x08, 0x75, 0x32, 0x72, 0xb1, 0x41,
	0xbc, 0x20, 0x64, 0x4b, 0xaa, 0x71, 0x28, 0xa1, 0x27, 0x65, 0x47, 0xae, 0x76, 0x98, 0x5b, 0x92,
	0xd8, 0xc0, 0x09, 0xc4, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xc4, 0xb7, 0x81, 0x43, 0x37, 0x02,
	0x00, 0x00,
}
