// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/jwt/jwt.proto

package com_github_romatroskin_viqchat_jwt_service_jwt

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Jwt service

func NewJwtEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Jwt service

type JwtService interface {
	Generate(ctx context.Context, in *GenerateRequest, opts ...client.CallOption) (*GenerateResponse, error)
}

type jwtService struct {
	c    client.Client
	name string
}

func NewJwtService(name string, c client.Client) JwtService {
	return &jwtService{
		c:    c,
		name: name,
	}
}

func (c *jwtService) Generate(ctx context.Context, in *GenerateRequest, opts ...client.CallOption) (*GenerateResponse, error) {
	req := c.c.NewRequest(c.name, "Jwt.Generate", in)
	out := new(GenerateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Jwt service

type JwtHandler interface {
	Generate(context.Context, *GenerateRequest, *GenerateResponse) error
}

func RegisterJwtHandler(s server.Server, hdlr JwtHandler, opts ...server.HandlerOption) error {
	type jwt interface {
		Generate(ctx context.Context, in *GenerateRequest, out *GenerateResponse) error
	}
	type Jwt struct {
		jwt
	}
	h := &jwtHandler{hdlr}
	return s.Handle(s.NewHandler(&Jwt{h}, opts...))
}

type jwtHandler struct {
	JwtHandler
}

func (h *jwtHandler) Generate(ctx context.Context, in *GenerateRequest, out *GenerateResponse) error {
	return h.JwtHandler.Generate(ctx, in, out)
}
