// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/jwt/jwt.proto

package com_github_romatroskin_viqchat_jwt_service_jwt

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GenerateRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Secret               string   `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateRequest) Reset()         { *m = GenerateRequest{} }
func (m *GenerateRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateRequest) ProtoMessage()    {}
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_976f9a388c6862c6, []int{0}
}

func (m *GenerateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateRequest.Unmarshal(m, b)
}
func (m *GenerateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateRequest.Marshal(b, m, deterministic)
}
func (m *GenerateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateRequest.Merge(m, src)
}
func (m *GenerateRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateRequest.Size(m)
}
func (m *GenerateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateRequest proto.InternalMessageInfo

func (m *GenerateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GenerateRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *GenerateRequest) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

type GenerateResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateResponse) Reset()         { *m = GenerateResponse{} }
func (m *GenerateResponse) String() string { return proto.CompactTextString(m) }
func (*GenerateResponse) ProtoMessage()    {}
func (*GenerateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_976f9a388c6862c6, []int{1}
}

func (m *GenerateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateResponse.Unmarshal(m, b)
}
func (m *GenerateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateResponse.Marshal(b, m, deterministic)
}
func (m *GenerateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateResponse.Merge(m, src)
}
func (m *GenerateResponse) XXX_Size() int {
	return xxx_messageInfo_GenerateResponse.Size(m)
}
func (m *GenerateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateResponse proto.InternalMessageInfo

func (m *GenerateResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*GenerateRequest)(nil), "com.github.romatroskin.viqchat.jwt.service.jwt.GenerateRequest")
	proto.RegisterType((*GenerateResponse)(nil), "com.github.romatroskin.viqchat.jwt.service.jwt.GenerateResponse")
}

func init() { proto.RegisterFile("proto/jwt/jwt.proto", fileDescriptor_976f9a388c6862c6) }

var fileDescriptor_976f9a388c6862c6 = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0x2a, 0x2f, 0x01, 0x61, 0x3d, 0x30, 0x4f, 0x48, 0x2f, 0x39, 0x3f, 0x57, 0x2f,
	0x3d, 0xb3, 0x24, 0xa3, 0x34, 0x49, 0xaf, 0x28, 0x3f, 0x37, 0xb1, 0xa4, 0x28, 0xbf, 0x38, 0x3b,
	0x33, 0x4f, 0xaf, 0x2c, 0xb3, 0x30, 0x39, 0x23, 0xb1, 0x44, 0x0f, 0xa4, 0xb2, 0x38, 0xb5, 0xa8,
	0x2c, 0x33, 0x39, 0x15, 0xc4, 0x56, 0xf2, 0xe7, 0xe2, 0x77, 0x4f, 0xcd, 0x4b, 0x2d, 0x4a, 0x2c,
	0x49, 0x0d, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91, 0x60,
	0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0xca, 0x4c, 0x11, 0x12, 0xe1, 0x62, 0x2d, 0xc8, 0xc8, 0xcf,
	0x4b, 0x95, 0x60, 0x02, 0x0b, 0x41, 0x38, 0x42, 0x62, 0x5c, 0x6c, 0xc5, 0xa9, 0xc9, 0x45, 0xa9,
	0x25, 0x12, 0xcc, 0x60, 0x61, 0x28, 0x4f, 0x49, 0x83, 0x4b, 0x00, 0x61, 0x60, 0x71, 0x41, 0x7e,
	0x5e, 0x71, 0x2a, 0xc8, 0x84, 0x92, 0xfc, 0xec, 0xd4, 0x3c, 0xa8, 0xa1, 0x10, 0x8e, 0xd1, 0x74,
	0x46, 0x2e, 0x66, 0xaf, 0xf2, 0x12, 0xa1, 0x7e, 0x46, 0x2e, 0x0e, 0x98, 0x16, 0x21, 0x7b, 0x12,
	0x3d, 0xa0, 0x87, 0xe6, 0x7a, 0x29, 0x07, 0xf2, 0x0d, 0x80, 0xb8, 0x56, 0x89, 0x21, 0x89, 0x0d,
	0x1c, 0x96, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xec, 0x5d, 0xc9, 0x10, 0x62, 0x01, 0x00,
	0x00,
}
